
import './css/style.less'
import './css/iconfont.css'
import './js/index.js'
// import {cube} from './math.js'
import jquery from 'jquery'
// import normalize from 'normalize'
import './css/common.css'
import './css/reset.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap/dist/js/bootstrap.min.js'